version: '3.3'  # version of compose format

services:
  landing-service:
    build: ./landing  # path is relative to docker-compose.yml location
    hostname: landing-service
    ports:
      - 5050:5050  # host:container
    networks:
      sample:
        aliases:
          - landing-service
  addition:
    build: ./addition  # path is relative to docker-compose.yml location
    hostname: addition-service
    ports:
      - 5051:5051  # host:container
    networks:
      sample:
        aliases:
          - addition-service
  division:
    build: ./division # path is relative to docker-compose.yml location
    hostname: division-service
    ports:
      - 5052:5052  # host:container
    networks:
      sample:
        aliases:
          - division-service
  equalto:
    build: ./equalto  # path is relative to docker-compose.yml location
    hostname: equalto-service
    ports:
      - 5053:5053  # host:container
    networks:
      sample:
        aliases:
          - equalto-service
  greater:
    build: ./greater  # path is relative to docker-compose.yml location
    hostname: greater-service
    ports:
      - 5054:5054  # host:container
    networks:
      sample:
        aliases:
          - greater-service
  lesser:
    build: ./lesser  # path is relative to docker-compose.yml location
    hostname: lesser-service
    ports:
      - 5055:5055  # host:container
    networks:
      sample:
        aliases:
          - lesser-service
  multiplication:
    build: ./multiplication  # path is relative to docker-compose.yml location
    hostname: multiplication-service
    ports:
      - 5056:5056  # host:container
    networks:
      sample:
        aliases:
          - multiplication-service
  substraction:
    build: ./substraction  # path is relative to docker-compose.yml location
    hostname: substraction-service
    ports:
      - 5057:5057  # host:container
    networks:
      sample:
        aliases:
          - substraction-service
networks:
  sample: